version: "3.8"
services:
  postgres:
    image: postgres:15.4
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-gestao-ativos
    ports:
      - "5432:5432"
      
networks:
  postgres:
    driver: bridge               